[package]
name = "oos"
version = "0.1.0"
edition = "2021"
description = "An integrated C language on the operating system API module, absolutely useful for all module developers!"
license = "MIT"

[dependencies]
